### ISSUE TITLE
Provide Maven BOM for OSGi Specs

### ISSUE THREAD

**Issue by kwin** [osgi/osgi#452] opened 2022-06-23 12:14 UTC
It would be nice to have a [Maven BOM](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms) per OSGi specification (Core and Compendium) that lists all most recent individual [OSGi chapter spec dependencies](http://docs.osgi.org/artifacts/#individual-artifacts). Often OSGi container are fully compliant with Core R7 or Compendium R7 so reusing an official BOM for doing the dependency management would be beneficial.

**Comment by bjhargrave** [comment] 2022-06-23 13:14
> Often OSGi container are fully compliant with Core R7 or Compendium R7 so reusing an official BOM for doing the dependency management would be beneficial.

I don't think this is true. Having a BOM is useful when a set of artifacts must be used together at prescribed versions. This can be true for the Jakarta EE platform,  the MicroProfile platform, Spring Framework, JUnit, etc. But OSGi is not like that. We do not define a platform. We publish a collection of specifications of which you are free to use in mixed and matched versions as desired. 

Furthermore, the OSGi build is not a maven build, so we have no way to ensure that any BOM we produce is a valid maven pom file and is even correct where the declared artifact versions match the versions of the actual artifacts produced by the build.

**Comment by bjhargrave** [comment] 2022-06-23 13:47
I will follow up by also noting that a BOM would have the same issues as the `osgi.cmpn` artifact that OSGi no longer publishes. It creates an implicit coupling between the OSGi specs in the BOM/osgi.cmpn when there is no actual coupling.

**Comment by bjhargrave** [comment] 2022-06-23 14:24
> All bundles from ASF Sling or ASF Felix which implement more than one spec use either Core R6, R7 or R8. Same for Compendium.

OK, but they do not implement every compendium spec. Just the ones they care about and even some of this may have had little attention recently.

> Do you have examples of OSGi bundles mixing different spec versions?

I have seen the issues with the implicit coupling caused by using `osgi.cmpn`. It caused the bundle to uplevel its use of any OSGi spec it touched. So if I have a bundle that uses Config Admin and also Promises, just because I need to use the latest Config Admin spec (to use some new feature) does not mean I want to use the latest Promise spec. I only use the features of the older Promise spec and want to maintain my import range on the older Promise API for maximum deployment flexibility. 

Using a BOM or `osgi.cmpn` causes me to use the latest Promise API at compile time which causes me to have a higher import range than I desire.

So I don't see that a BOM is a good thing when there is no actual version coupling between all the elements in the BOM. For JUnit it makes sense, you want to use all the desired JUnit artifacts at the matching versions prescribed by the BOM.

I recently went through a whole effort in the OSGi build to remove the use of `osgi.cmpn` so that each spec API project uses the individual API artifacts for any dependencies on other OSGi specs at the lowest versions needed by the spec. This means that, for example, the `org.osgi.service.component` spec API project uses the `org.osgi.util.promise` API at version 1.0 even though the latest `org.osgi.util.promise` API is version 1.2.

This is how people should develop: compile low, run high. And a BOM (or `osgi.cmpn`) does not support compile low as people will tend to use the latest BOM to get access to some new spec version they need and then compile against higher versions of other OSGi specs when the really do not need to. When this happens it makes resolving a system much harder since you may not be able to deploy a bundle without also updating all dependencies since the bundle compiled high.

**Comment by kwin** [comment] 2022-06-23 14:26
> OK, but they do not implement every compendium spec. Just the ones they care about and even some of this may have had little attention recently.

Exactly, that is also why a BOM only defines dependencyManagement (i.e. you still need to reference the needed chapter dependencies, just without version)

**Comment by bjhargrave** [comment] 2022-06-23 14:39
> Exactly, that is also why a BOM only defines dependencyManagement (i.e. you still need to reference the needed chapter dependencies, just without version)

And this is dangerous as it create implicit version coupling. Felix SCR needs to implement the DS spec at the latest version. The DS spec uses the Promise spec but only at the 1.0 version. The BOM will expose Felix SCR to the latest version (1.2) of the Promise spec which means that Felix SCR will import the highest version of the Promise spec when it only needs the 1.0 version of the Promise spec. So Felix SCR will not be able to be deployed when the Promise API is only available at version 1.0.

The best choice for Felix SCR is to use the oldest version of Promise consistent with its actual needs not just that latest version because the BOM specifies the latest version.

**Comment by kwin** [comment] 2022-06-23 14:45
> So Felix SCR will not be able to be deployed when the Promise API is only available at version 1.0.

Right, but isn't this a very theoretical case? Which OSGi container has DS 1.5 but Promise 1.0?

> The best choice for Felix SCR is to use the oldest version of Promise consistent with its actual needs not just the latest version because the BOM specifies the latest version.

I agree with that principle, still managing all spec chapters versions individually is often painful, therefore developers stay with the worse aggregate dependencies. A BOM would not prevent anyone from defining versions themselves. I rather see it as vehicle to migrate from aggregate to individual spec dependencies.

**Comment by bjhargrave** [comment] 2022-06-23 14:51
> Which OSGi container has DS 1.5 but Promise 1.0?

You keep saying "OSGi container" like it is a defined platform. OSGi usage is a framework plus whatever bundles you want.



> Right, but isn't this a very theoretical case?

In my experience it is not theoretical and is the reason OSGi retired the `osgi.cmpn` artifact.



> I rather see it as vehicle to migrate from aggregate to individual spec dependencies with less effort.

I don't see how it does that since one must still specify the dependency in their POM. The BOM only removes the need to include the version. And my argument is that this is a problem. The developer needs to choose the lowest version that is necessary and not the latest version specified in the BOM.

**Comment by bjhargrave** [comment] 2022-06-23 14:56
> > Right, but isn't this a very theoretical case?
> 
> In my experience it is not theoretical and is the reason OSGi retired the `osgi.cmpn` artifact.

In fact the `osgi-test` project deals with this in regard to the Promise API version:

https://github.com/osgi/osgi-test/blob/ad65c29d0eddb15f6b5a40f6b40bbb734516ea4e/pom.xml#L54-L57

The project needs to support users with Promise 1.0 and so it compiles against Promise 1.0, but it also needs to test against the latest version.

**Closed as completed** 2022-07-20 15:56 UTC
